#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Surgiie\BladeCLI\Application;
use Surgiie\BladeCLI\Commands\RenderCommand;

define('BLADE_CLI_VERSION', 'V2.0.6');

$app = new Application('', BLADE_CLI_VERSION);

$app->add(new RenderCommand);

$app->run();
