#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Surgiie\BladeCLI\Commands\RenderCommand;
use Symfony\Component\Console\Application;

define('BLADE_CLI_VERSION', '2.0.0');

$app = new Application('Blade CLI', BLADE_CLI_VERSION);

$app->add(new RenderCommand);

$app->run();
