#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Surgiie\BladeCLI\Commands\RenderCommand;
use Surgiie\BladeCLI\Support\ConsoleApplication;

define('BLADE_CLI_VERSION', 'V2.0.3');

$app = new ConsoleApplication('', BLADE_CLI_VERSION);

$app->add(new RenderCommand);

$app->run();
